name: CI - Automacao Instagram

# on:
#   schedule:
#     - cron: "0 6 1 * *"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes (pytest)
        run: |
          pytest

      - name: Upload PDFs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorios-gerados
          path: |
            outputs/**/*.pdf

      - name: Run pipeline
        run: |
          python main.py